services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medistry_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-medistry-test.sql:/docker-entrypoint-initdb.d/init-medistry-test.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      target: development
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medistry_dev
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    command: npm run dev
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"

  test-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medistry_test
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  postgres-data:
  test-postgres-data:
